server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cstjubogph6c739fgvu0-a.oregon-postgres.render.com:5432/banco_wsge
        # url: jdbc:postgresql://localhost:8080/niloinvest
        username: banco_wsge_user
        password: 73RHK826yS3eweE4tD4AXndJPvwhpF0O
        driver-class-name: org.postgresql.Driver
        # spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
        initialize: true
    
    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres